name: Newman API Tests
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *"
jobs:
  test:
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v2

      - name: Set up node version
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: "Install newman"
        run: "npm install -g newman"

      - name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      - name: "Run tests"
        run: "newman run Library.postman_collection.json -e UAT.postman_environment.json newman -r htmlextra --reporter-htmlextra-export htmlreport.html --reporter-htmlextra-darkTheme"
      - name: Display contents
        run: ls
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: htmlreport.html
